### ISSUE TITLE
EtherSpotFleet resource fails to create

### ISSUE THREAD

**Issue by chris-downs** [JamesSWiggins/EthMiningCFN#1]
The following resource(s) failed to create: [EtherSpotFleetuseast1]

``` Invalid: (InstanceType: g3.4xlarge,Os: generic,Addressing: nat),(InstanceType: g3.8xlarge,Os: generic,Addressing: nat),(InstanceType: g3.16xlarge,Os: generic,Addressing: nat),(InstanceType: p2.xlarge,Os: generic,Addressing: nat),(InstanceType: p2.8xlarge,Os: generic,Addressing: nat),(InstanceType: p2.16xlarge,Os: generic,Addressing: nat),```

Any ideas?

**Comment by sinejoe** [comment]
Same error. Thinking it's the "Os: generic" attribute which must be defined in the AMIs because not present in the template file?

**Comment by JamesSWiggins** [comment]
Were you deploying in N. Virginia (us-east-1)?

**Comment by chris-downs** [comment]
Yes, I just confirmed that I cannot repro in us-east-2 so it looks to be specific to us-east-1.

**Comment by JamesSWiggins** [comment]
Hmm... I just deployed using the template in us-east-1 and that's also where I did most of my testing...  Was there more to the error message?  This showed up in the CloudFormation Events log?

**Comment by chris-downs** [comment]
It shows up in the "Events" output when creating the stack. 
![screenshot from 2017-10-03 13-00-25](https://user-images.githubusercontent.com/4074377/31140719-e0b6fe48-a83a-11e7-8d18-f55943f473a7.png)

**Comment by JamesSWiggins** [comment]
Hey Chris, could you try the branch I just created for you?  This may be due to some older instance types not being available to all AWS accounts.

**Comment by chris-downs** [comment]
Still the same error- I also compared the list of instance types in the template from master to what is available for me to launch in Virginia and they seem to all be available. 

When I expand the error line it just reveals:
```
Client Request Token:Console-CreateStack-32ba13fe-34c9-4582-a0d1-b6d8559c24ac
```

**Comment by JamesSWiggins** [comment]
Just curious, what does your Parameters section look like for that deployment?

**Comment by chris-downs** [comment]
I just used the defaults for that last test-

FleetSize | 1
SpotPrice | 0.2
Wallet | 0xf395eed96579a679859dacaf0bfda096f18fbffb

**Comment by chris-downs** [comment]
This smells like a bug in SpotFleet. Everything works fine in the Ohio region and the metadata for the AMIs in Ohio and Virginia looks the same.

**Comment by JamesSWiggins** [comment]
I'm really at a loss.  I did get an error like that while testing and it was due to my attempting to launch a Spot Fleet that included Instance Types that didn't exist in the Region I was in.  That was what caused me to branch the CFN Template to have four different Spot Fleet resources that were tied to Region conditions.  I'm not able to replicate what you're experiencing yet...

**Comment by chris-downs** [comment]
I'm okay with playing around with this in the Ohio region, so no big deal for me. Let me know if I can help you test anything else though!
